### ISSUE TITLE
connection causes restart

### ISSUE THREAD

**Issue by damianburrin** [ntoll/microfs#1]
Hi Nick
I seem to be getting unusual behaviour from MicroFS

I'm writing a simple P.O.C datalogger for a drone as and example to use in school but coming up with what appears to me to be unusual behaviour when using MicroFS

If you consider the code below which is nothing more than the demo code activated by a button

from microbit import *
while True:
    if button_a.is_pressed():
        with open("test.txt", "w") as myfile:
            myfile.write("Time,X,Y,Z,\n")
            myfile.close()
            break

When you run the microbit and press b all seems good, when you go to python and use MicroFS and call the ls() command it just sits there.  
If you press button b again the code running MicroFS will then error calling ls() at this point gets the directory list.
calling get() generates the same behaviour hangs, press b file downloads.

It's almost as if the call from python shell to use ls() or get() etc restarts the programme running on the Micro:bit which seems to me to be odd behaviour.  Once you've ran the code and in my case logged the data and exited so the code on the microbit is no longer running you don't want the code/commands to list and download the data to restart the Micro:bit and restart the programme running on it.

Is this making sense or am I missing the point?

Thank you
Damian

**Comment by ntoll** [comment]
Hi @damianburrin,

This is expected behaviour. It's down to the way microfs works: In order to run the various commands microfs connects to the device and runs remote Python code against the REPL and processes the result. 

For this to happen, the device needs to break out of any loop it may be in - so microfs sends various control-codes to the device (basically CTRL-C) to stop any currently running script. Then, it needs to put the device into "raw" mode (which means it's possible to read/write data easily from/to the REPL). Only then can microfs run the command and processes any response it gets. Finally, to return the device to "normal" mode, microfs restarts the device.

This happens for *each* command sent to the device. If you're interested in how the code works you should take a look here: 

https://github.com/ntoll/microfs/blob/master/microfs.py#L52

Does this make sense?

**Comment by damianburrin** [comment]
?Does this make sense?

Yes I think so. I’ll keep looking and reading.

Thank you

Damian

**Comment by damianburrin** [comment]
I guess this sort of explains why i’m getting the contents of the repl as the file contents and not the data i’m writing to it as well

Hmm – more thinking to do here.  Reading and Writing to the Microbit is not as simple as i’d hoped.

Will keep working on it.

**Comment by dpgeorge** [comment]
It's possible to improve the behaviour of connecting to the microbit and entering/leaving raw REPL, via:
```
enter:
   ctrl-C
   flush_input
   ctrl-A
   ctrl-D

exit:
    ctrl-B
```
This will make sure that the main script (or appended hex file) is never executed when you execute a command via raw REPL.  See tools/pyboard.py for details (enter_raw_repl and exit_raw_repl methods).

**Comment by ntoll** [comment]
Aha... I should have checked. ;-)

This'll be useful for Mu - I'm currently working on a visual drag-drop-delete widget for kids and teachers.

**Comment by dpgeorge** [comment]
Ideally you'd import pyboard.py, but I understand you want a "one file solution".  In that case just cut-and-paste the relevant code from pyboard.py.

**Comment by ntoll** [comment]
Greetings from a train heading towards Milton Keynes!

@dpgeorge got it in one - I'm after a simple stand-alone command.
@damianburrin have you tried logging data in new files after they reach a certain size limit (in a way that's similar to how logs can be "rolled-over"). Actually, you're essentially logging things anyway. :-)

In any case, I've just spent 15 minutes updating (simplifying) the `execute` method so it won't restart the device and follows the same sort of commands as PyBoard. You should be able to update it from PyPI.

It's at version 1.0.3 now. If there are any more problems please create a new ticket! I'll mark this one as closed since it solves your immediate restart-related issue.

**Comment by damianburrin** [comment]
Brill i will give it a crack @ntoll thankyou.
I was looking at logging and rolling over thw file but the issue is not the file size, ive yet for one to break the 1k value.  The issue there is that as their is no append you are constantly reading into to a variable adding the variable to itself and writing ot back as a new file (this is whatvthe doc says to do to replace append)  this causes the variable to get to large and you run out of memory long before getting amywhere near 32K.
Im not sure if there is a way to limit the size of the variable before you update it and write back but i'll have a look.
Thankyou
Damian
On 21 Jun 2016 17:41, Nicholas Tollervey <notifications@github.com> wrote:Greetings from a train heading towards Milton Keynes!

@dpgeorge got it in one - I'm after a simple stand-alone command.
@damianburrin have you tried logging data in new files after they reach a certain size limit (in a way that's similar to how logs can be "rolled-over"). Actually, you're essentially logging things anyway. :-)

In any case, I've just spent 15 minutes updating (simplifying) the execute method so it won't restart the device and follows the same sort of commands as PyBoard. You should be able to update it from PyPI.

It's at version 1.0.3 now. If there are any more problems please create a new ticket! I'll mark this one as closed since it solves your immediate restart-related issue.

**Comment by damianburrin** [comment]
fix confirmed @ntoll you truly are ace
