### ISSUE TITLE
File Limits

### ISSUE THREAD

**Issue by damianburrin** [ntoll/microfs#2]
Hi @ntoll 

I'm trying to put my own python lib on the microbit so I can call it later.  The file is 4k (well 3.58kb) but when I upload the file using put it get the following error message

  File "C:\Python34\lib\site-packages\microfs.py", line 131, in put
    raise IOError(clean_error(err))
OSError: MemoryError: memory allocation failed, allocating 2480 bytes

I'm assuming it a file size limit.  The microbit does not have anything flashed on it at all so I should be well inside the 32k limit.

Any ideas?

Thanks
Damian

**Comment by dpgeorge** [comment]
The microbit might not have enough RAM to store the whole file before copying to the flash storage.  To fix it the file will need to be copied in pieces.

**Comment by damianburrin** [comment]
Ok thanks.  Looks like that will be the job for this week :-)
The micro:bit has 16k of RAM available and 256K flash but i guess a lot gets used up on  resources while running.
Will play.
Thanks again
On 26 Jun 2016 22:10, Damien George <notifications@github.com> wrote:The microbit might not have enough RAM to store the whole file before copying to the flash storage.  To fix it the file will need to be copied in pieces.

**Comment by damianburrin** [comment]
Hmm - It would make life a lot easier if there was an append option, with would enable the ability to build up a file over time rather than trying to store it all in memory before moving to flash.

I guess the need to keep it light weight overrides the need for append.

Will keep plugging away

**Comment by ntoll** [comment]
@damianburrin I was looking through this code over the weekend and there was a bug in the naive first implementation I'd written. It's now fixed and you'll be able to put/get files of arbitrary size (it does what Damien suggests - chunks the read/write into pieces). However, this doesn't address your append-related query. 

Since I've addressed the initial (non-append) bug report, I'm closing the issue. Thanks for the feedback! Keep it coming. :-)

**Comment by damianburrin** [comment]
Great stuff

Damian
