### ISSUE TITLE
failing to connect

### ISSUE THREAD

**Issue by damianburrin** [ntoll/microfs#3]
Hi Nic,

I've just updated to the latest version and am getting some issues.
form python after importing microfs I used to be able just to call ls() for example to read the files on the microbit.  That now gives me a serial error ad suggests I need to include a port (TypeError: ls() missing 1 required positional argument: 'serial'). 

 If I use ls(5) for example for com5 I get error messages.  I must be doing something silly.

Any help appreciated.

DAmian

**Comment by Elrengoo** [comment]
No consolation but I get the same. ls seems to require a serial port id and put/get/rm require serial port and filename. Presumably it is failing to find the microbit and allocate a channel???

**Comment by damianburrin** [comment]
@ntoll has mentioned that this is being “unbroken” on the next update

Damian

**Comment by ntoll** [comment]
Currently fixing it as we speak.

In the first version you didn't have to supply a serial object and every command was "atomic". This was problematic since you should be able to re-use a serial connection to run several commands if you're interacting with the module from a script. Hence the change. However, I'm making the serial object optional so you can both pass in a long running connection or just expect the module to figure it out for you.

Does this make sense?

**Comment by ntoll** [comment]
Fixed by f95723d86439e5e39331d32c1cb9188d1d244a50

Pushed to PyPI.

**Comment by damianburrin** [comment]
Just tested.  Fix confirmed.

Thank you
